language: ruby
rvm:
  - 2.0.0-p353

before_install:
  - gem update --system
  - gem --version
  - psql -c 'create database greenmonkeychess_test;' -U postgres 

before_script:
 - bundle exec rake assets:precompile
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec