language: ruby
rvm:
  - 2.0.0-p353

before_install:
  - gem update --system
  - gem --version
  - rake db:create:all
  - rake db:migrate

before_script:
 - bundle exec rake assets:precompile
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec